version: "3.8"

services:
  jenkins-docker:
      image: docker:dind
      container_name: jenkins-docker
      restart: unless-stopped
      privileged: true
      networks:
        jenkins:
          aliases:
            - docker
      environment:
        - DOCKER_TLS_CERTDIR=/certs
      volumes:
        - jenkins-docker-certs:/certs/client
        - jenkins-data:/var/jenkins_home
      ports:
        - "2376:2376"
      command: --storage-driver overlay2

  jenkins-blueocean:
      build:
        context: .
      image: myjenkins-blueocean
      container_name: jenkins-blueocean
      restart: unless-stopped
      networks:
        - jenkins
      environment:
        - DOCKER_HOST=tcp://docker:2376 
        - DOCKER_CERT_PATH=/certs/client
        - DOCKER_TLS_VERIFY=1
      ports:
        - "8080:8080"   
        - "50000:50000"
      volumes:
        - jenkins-data:/var/jenkins_home
        - jenkins-docker-certs:/certs/client:ro

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-docker-certs: