version: "3.8"

services:
  jenkins:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: "jenkins/jenkins:lts"
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data/jenkins:/var/jenkins_home
    restart: unless-stopped
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge